# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b81fa41f58a8802239feee9681f3d6bf82e0dceaef5719efe66cc265caa4c48af5d122dac74471570dddd7f5d692490bb64c41c6311dbc146dbed3952fe2fbb

test:
  secret_key_base: d54a08e785ff1659e4f9c563712d8e0708e88313bc78c3dcddb73bc0cf55d03c84267e72afc9f9077e432aff848bbf4778cf857a8ab2493d020470dfc62d56c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
